# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  secret_key_base: 7ffd2b4cf6c6b47f6adb2dfea600432d37a1799385103282d8a814da5c6feb21cee24271fd89a8d45ae6fa1a3633c19d32fc9b07a70f4a5935eb163519b332d7

test:
  secret_key_base: 3888ecc739a518c7b1f2e13a2d53107942b0c0948550009bd8fec4c626f832b75da74c5257a4e12cd025819dce5612133b2f05f79f5951629c516e6f669612dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
